# Generated by Django 4.0.6 on 2022-07-26 18:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QCMChamp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_text', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='QuestionChoixMultiple',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_text', models.CharField(max_length=300)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='QuestionLibre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_text', models.CharField(max_length=300)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Questionnaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_text', models.CharField(max_length=100)),
                ('MONTHSTART_START', models.DateTimeField()),
                ('MONTHSTART_END', models.DateTimeField()),
                ('MONTHEND_START', models.DateTimeField()),
                ('MONTHEND_END', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='QuestionSlider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_text', models.CharField(max_length=300)),
                ('value_min', models.IntegerField()),
                ('value_max', models.IntegerField()),
                ('questionnaire_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ddrs_api.questionnaire')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_text', models.CharField(max_length=30)),
                ('privilege_int', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ReponseSlider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_date', models.DateTimeField(blank=True, null=True)),
                ('answer_value', models.IntegerField()),
                ('question_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='ddrs_api.questionslider')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ddrs_api.utilisateur')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ReponseLibre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_date', models.DateTimeField(blank=True, null=True)),
                ('answer_text', models.CharField(max_length=300)),
                ('question_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='ddrs_api.questionlibre')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ddrs_api.utilisateur')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ReponseChoixMultiple',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_date', models.DateTimeField(blank=True, null=True)),
                ('question_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='ddrs_api.questionchoixmultiple')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ddrs_api.utilisateur')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RCMChamp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checked_boolean', models.BooleanField(default=False)),
                ('qcmchamp_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='ddrs_api.qcmchamp')),
                ('rcm_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ddrs_api.reponsechoixmultiple')),
            ],
        ),
        migrations.AddField(
            model_name='questionlibre',
            name='questionnaire_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ddrs_api.questionnaire'),
        ),
        migrations.AddField(
            model_name='questionchoixmultiple',
            name='questionnaire_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ddrs_api.questionnaire'),
        ),
        migrations.AddField(
            model_name='qcmchamp',
            name='question_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ddrs_api.questionchoixmultiple'),
        ),
    ]
