# Generated by Django 4.0.6 on 2022-07-21 00:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ddrs_api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='sign_date',
        ),
    ]
