# Generated by Django 4.0.6 on 2022-07-23 17:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ddrs_api', '0002_remove_user_sign_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='QCMChamp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_text', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='QuestionChoixMultiple',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_text', models.CharField(max_length=300)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='QuestionLibre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_text', models.CharField(max_length=300)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Questionnaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_text', models.CharField(max_length=100)),
                ('MONTHSTART_START', models.DateField()),
                ('MONTHSTART_END', models.DateField()),
                ('MONTHEND_START', models.DateField()),
                ('MONTHEND_END', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='QuestionSlider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_text', models.CharField(max_length=300)),
                ('value_min', models.IntegerField()),
                ('value_max', models.IntegerField()),
                ('questionnaire_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ddrs_api.questionnaire')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RCMChamp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qcmchamp_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ddrs_api.qcmchamp')),
            ],
        ),
        migrations.CreateModel(
            name='ReponseChoixMultiple',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_date', models.TimeField()),
                ('question_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ddrs_api.questionchoixmultiple')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ReponseLibre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_date', models.TimeField()),
                ('answer_text', models.CharField(max_length=300)),
                ('question_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ddrs_api.questionlibre')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ReponseSlider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_date', models.TimeField()),
                ('answer_value', models.IntegerField()),
                ('question_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ddrs_api.questionslider')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_text', models.CharField(max_length=30)),
                ('privilege_int', models.PositiveIntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='User',
        ),
        migrations.AddField(
            model_name='reponseslider',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ddrs_api.utilisateur'),
        ),
        migrations.AddField(
            model_name='reponselibre',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ddrs_api.utilisateur'),
        ),
        migrations.AddField(
            model_name='reponsechoixmultiple',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ddrs_api.utilisateur'),
        ),
        migrations.AddField(
            model_name='rcmchamp',
            name='rcm_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ddrs_api.reponsechoixmultiple'),
        ),
        migrations.AddField(
            model_name='questionlibre',
            name='questionnaire_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ddrs_api.questionnaire'),
        ),
        migrations.AddField(
            model_name='questionchoixmultiple',
            name='questionnaire_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ddrs_api.questionnaire'),
        ),
        migrations.AddField(
            model_name='qcmchamp',
            name='question_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ddrs_api.questionchoixmultiple'),
        ),
    ]
