# Generated by Django 4.0.6 on 2022-08-12 13:33

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ddrs_api', '0002_alter_reponsechoixmultiple_user_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rcmchamp',
            name='qcmchamp_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ddrs_api.qcmchamp'),
        ),
        migrations.AlterField(
            model_name='reponsechoixmultiple',
            name='answer_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='reponsechoixmultiple',
            name='question_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ddrs_api.questionchoixmultiple'),
        ),
        migrations.AlterField(
            model_name='reponselibre',
            name='answer_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='reponselibre',
            name='question_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ddrs_api.questionlibre'),
        ),
        migrations.AlterField(
            model_name='reponseslider',
            name='answer_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='reponseslider',
            name='question_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ddrs_api.questionslider'),
        ),
    ]
