# Generated by Django 4.1 on 2022-08-22 14:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ddrs_api', '0002_alter_reponsechoixmultiple_user_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='qcmchamp',
            old_name='question_id',
            new_name='question',
        ),
        migrations.RenameField(
            model_name='questionchoixmultiple',
            old_name='questionnaire_id',
            new_name='questionnaire',
        ),
        migrations.RenameField(
            model_name='questionlibre',
            old_name='questionnaire_id',
            new_name='questionnaire',
        ),
        migrations.RenameField(
            model_name='questionslider',
            old_name='questionnaire_id',
            new_name='questionnaire',
        ),
        migrations.RenameField(
            model_name='rcmchamp',
            old_name='qcmchamp_id',
            new_name='qcmchamp',
        ),
        migrations.RenameField(
            model_name='rcmchamp',
            old_name='rcm_id',
            new_name='rcm',
        ),
        migrations.RenameField(
            model_name='reponsechoixmultiple',
            old_name='question_id',
            new_name='question',
        ),
        migrations.RenameField(
            model_name='reponsechoixmultiple',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='reponselibre',
            old_name='question_id',
            new_name='question',
        ),
        migrations.RenameField(
            model_name='reponselibre',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='reponseslider',
            old_name='question_id',
            new_name='question',
        ),
        migrations.RenameField(
            model_name='reponseslider',
            old_name='user_id',
            new_name='user',
        ),
        migrations.AlterField(
            model_name='reponsechoixmultiple',
            name='answer_date',
            field=models.DateTimeField(auto_now=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='reponselibre',
            name='answer_date',
            field=models.DateTimeField(auto_now=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='reponseslider',
            name='answer_date',
            field=models.DateTimeField(auto_now=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
