# Generated by Django 4.0.6 on 2022-07-23 17:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ddrs_api', '0003_qcmchamp_questionchoixmultiple_questionlibre_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rcmchamp',
            name='checked_boolean',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='rcmchamp',
            name='qcmchamp_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='ddrs_api.qcmchamp'),
        ),
        migrations.AlterField(
            model_name='reponsechoixmultiple',
            name='answer_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='reponsechoixmultiple',
            name='question_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='ddrs_api.questionchoixmultiple'),
        ),
        migrations.AlterField(
            model_name='reponselibre',
            name='answer_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='reponselibre',
            name='question_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='ddrs_api.questionlibre'),
        ),
        migrations.AlterField(
            model_name='reponseslider',
            name='answer_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='reponseslider',
            name='question_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='ddrs_api.questionslider'),
        ),
    ]
