# Generated by Django 4.0.6 on 2022-08-12 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ddrs_api', '0003_alter_rcmchamp_qcmchamp_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rcmchamp',
            name='checked_boolean',
        ),
    ]
